export const GET_SWITCHES = 'GET_SWITCHES';
export const FILTER_SWITCHES_NAME = 'FILTER_SWITCHES_NAME';
export const FILTER_SWITCHES_TYPE = 'FILTER_SWITCHES_TYPE';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const SET_DETAILS = 'SET_DETAILS';